name: main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  hello:
    runs-on: windows10-01
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hellomoto!"
        shell: cmd

  goodbye:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v2
      - name: goodbye
        run: echo "Bye bye"
        shell: bash